export const IPC_CHANNELS = {
  appGetState: 'app:get-state',
  appAddSession: 'app:add-session',
  appRemoveSession: 'app:remove-session',
  appOpenExternalDirectory: 'app:open-external-directory',
  appOpenLogDirectory: 'app:open-log-directory',
  appSelectDirectory: 'app:select-directory',
  appShortcut: 'app:shortcut',
  appUpdateAuthConfiguration: 'app:update-auth-configuration',
  appUpdateShellConfiguration: 'app:update-shell-configuration',
  appUpdateClaudeConfiguration: 'app:update-claude-configuration',
  appUpdateDeckPreferences: 'app:update-deck-preferences',
  appUpdateAudioPreferences: 'app:update-audio-preferences',
  appUpdateNotificationPreferences: 'app:update-notification-preferences',
  appUpdateSessionConfiguration: 'app:update-session-configuration',
  appUpdateSessionOrder: 'app:update-session-order',
  appUpdateSessionAudioPreferences: 'app:update-session-audio-preferences',
  claudeDiscover: 'claude:discover',
  authCheck: 'auth:check',
  authStartRefresh: 'auth:start-refresh',
  authWrite: 'auth:write',
  authResize: 'auth:resize',
  authStopRefresh: 'auth:stop-refresh',
  authOutput: 'auth:output',
  authExit: 'auth:exit',
  terminalGetShellOptions: 'terminal:get-shell-options',
  terminalStartShell: 'terminal:start-shell',
  terminalPrepareClaude: 'terminal:prepare-claude',
  terminalStartClaude: 'terminal:start-claude',
  terminalWrite: 'terminal:write',
  terminalResize: 'terminal:resize',
  terminalStop: 'terminal:stop',
  terminalGetSnapshots: 'terminal:get-snapshots',
  terminalOutput: 'terminal:output',
  terminalExit: 'terminal:exit',
  terminalState: 'terminal:state',
  terminalConversationBinding: 'terminal:conversation-binding',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
